name: Java CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[CI skip]') == false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
    - name: 设置 JDK 17
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 17
    - name: 使用 Maven 构建
      run: mvn package --file pom.xml
    - name: 自动释放
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "jar"
        prerelease: true
        title: "DyeBench 自动构建版本"
        files: |
           target/*
    - name: 上传 The Bruh
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
           target/*